services:
  backend:
    image: maven:3.9.9-eclipse-temurin-21
    working_dir: /app
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    networks:
      - eventease-network

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8080/api
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - eventease-network

networks:
  eventease-network:
    driver: bridge
